- id: home_assistant_mqtt_checkup
  alias: Home Assistant MQTT checkup
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/POWER
      payload: ''
